# spell-checker:ignore Buildx buildx stefanzweifel
name: Build KuZu Lite

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: [self-hosted, macOS, ARM64]
          - arch: amd64
            runner: [self-hosted, Linux, X64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run in Docker
      run: |
        docker build -t kuzu-lite-build -f- . <<EOF
        FROM node:18-alpine
        RUN apk add --no-cache g++ build-base python3 make cmake zlib-dev musl-dev git
        WORKDIR /app
        COPY . .
        RUN yarn remove kuzu || true
        RUN yarn add kuzu
        WORKDIR /app/node_modules/kuzu/kuzu-source/tools/nodejs_api
        RUN yarn install
        RUN yarn build
        RUN mkdir -p ../../../prebuilt
        RUN cp -f ./build/kuzujs.node ../../../prebuilt/kuzujs-alpine-${{ matrix.arch }}.node
        WORKDIR /app
        RUN yarn build
        RUN cp -f /app/prebuilt/kuzujs-alpine-${{ matrix.arch }}.node kuzujs.node
        RUN cd util
        RUN node ./test.js || echo "test_failed=true" >> $GITHUB_OUTPUT
        EOF

        docker create --name kuzu-lite-build-container kuzu-lite-build
        docker cp kuzu-lite-build-container:/app/node_modules/kuzu/prebuilt/. ./prebuilt/
        docker rm kuzu-lite-build-container

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--no-verify'
        add: 'prebuilt/*.node *.js'
        message: "Add compiled kuzujs-alpine-${{ matrix.arch }}.node for kuzu v${{ needs.check-versions.outputs.kuzu_version }} [skip ci]"
